---
title: "Question 8.2"
author: "Siddharth Gandhi"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r Question 8.2}

#Load libary
library(stats); library(caret)

#Load Data
data <- read.table("C:\\Users\\Sid\\OneDrive\\Desktop\\Data 8.2\\uscrime.txt", stringsAsFactors = F, header = T)

#Baseline Model
crime_bm <- lm(Crime ~., data)
summary(crime_bm)

#Test data
test <- data.frame(M = 14.0, So = 0, Ed = 10.0, Po1 = 12.0, Po2 = 15.5,
                      LF = 0.640,
                      M.F = 94.0,
                      Pop = 150,
                      NW = 1.1,
                      U1 = 0.120,
                      U2 = 3.6,
                      Wealth = 3200,
                      Ineq = 20.1,
                      Prob = 0.04,
                      Time = 39.0)

model_pred1 <- predict(crime_bm, test)
model_pred1

#Adjust the crime_bm model and keep predictors with p < 0.1
crime_adj <- lm(Crime ~ M + Ed + Po1 + U2 + Ineq + Prob, data)
summary(crime_adj)

model_pred2 <- predict(crime_adj, test)
model_pred2

#Model quality checks
model1_ctrl <- trainControl(method="cv", number = 10)
model1_cv <- train(Crime ~., data, trControl = model1_ctrl, method = "lm",
                   na.action = na.pass)
model1_cv

model2_ctrl <- trainControl(method="cv", number = 10)
model2_cv <- train(Crime ~ M + Ed + Po1 + U2 + Ineq + Prob, data, 
                   trControl = model2_ctrl, method = "lm",
                   na.action = na.pass)
model2_cv
```

